const { getSupabaseClient, getGeminiClient, extractVoiceProfile } = require('./shared');

exports.handler = async (event) => {
  const headers = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Content-Type': 'application/json',
  };
  if (event.httpMethod === 'OPTIONS') return { statusCode: 200, headers, body: '' };
  if (event.httpMethod !== 'POST') return { statusCode: 405, headers, body: JSON.stringify({ error: 'Method not allowed' }) };

  try {
    const body = JSON.parse(event.body || '{}');
    const { id, type, outcome } = body; // type is either 'history' or 'example'

    if (!id || !outcome) {
      return {
        statusCode: 400,
        headers,
        body: JSON.stringify({ error: 'ID and outcome are required' })
      };
    }

    const supabase = getSupabaseClient();
    const ai = getGeminiClient();

    let outcomeScore = 50;
    if (outcome === 'booked') outcomeScore = 100;
    if (outcome === 'replied') outcomeScore = 50;
    if (outcome === 'ghosted') outcomeScore = 0;

    let updatedRow = null;
    let voiceRefreshed = false;

    if (type === 'example') {
      const { data, error } = await supabase
        .from('pitch_examples')
        .update({ outcome, outcome_score: outcomeScore })
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      updatedRow = data;
      
      // Refresh voice profile since an example's outcome changed
      const refreshResult = await extractVoiceProfile(supabase, ai);
      voiceRefreshed = !!refreshResult.profile;

    } else {
      // type === 'history'
      const { data: historyRow, error: fetchErr } = await supabase
        .from('pitch_history')
        .select('*')
        .eq('id', id)
        .single();

      if (fetchErr) throw fetchErr;

      const { data, error } = await supabase
        .from('pitch_history')
        .update({ outcome, outcome_score: outcomeScore })
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;
      updatedRow = data;

      // If the outcome is positive (replied or booked), add it to pitch_examples
      if (outcome === 'booked' || outcome === 'replied') {
        const textToSave = historyRow.final_sent || historyRow.ai_draft;
        
        if (textToSave) {
          // Check if it already exists in examples
          const { data: existing } = await supabase
            .from('pitch_examples')
            .select('id')
            .eq('content', textToSave)
            .maybeSingle();

          if (!existing) {
            // Insert into examples
            const { error: exampleErr } = await supabase
              .from('pitch_examples')
              .insert({
                channel: historyRow.channel || 'email',
                venue_type: historyRow.venue_type || null,
                gap_type: historyRow.gap_type || null,
                content: textToSave,
                outcome,
                outcome_score: outcomeScore,
                is_user_example: false // generated by AI, validated by outcome
              });

            if (!exampleErr) {
              // Trigger voice profile refresh
              const refreshResult = await extractVoiceProfile(supabase, ai);
              voiceRefreshed = !!refreshResult.profile;
            } else {
              console.error('Failed to copy to pitch_examples:', exampleErr);
            }
          }
        }
      }
    }

    return {
      statusCode: 200,
      headers,
      body: JSON.stringify({
        success: true,
        updatedRow,
        voiceRefreshed
      })
    };

  } catch (err) {
    console.error('update-outcome error:', err);
    return {
      statusCode: 500,
      headers,
      body: JSON.stringify({ error: 'Failed to update outcome: ' + err.message })
    };
  }
};
